### ISSUE TITLE
Integração de API Github para exibição dos colaboradores do projeto

### ISSUE THREAD

**Issue by mikaelhadler** [Ongbook/front-ng2-bootstrap-test#4]
Fazer sessão de "colaboradores" trazendo as informações disponíveis pela api do Github  [https://developer.github.com/v3/](url) na parte institucional do site (homepage).
- Imagem de avatar do usuário ancorado para seu perfil no github (se possível)

**Comment by edoura** [comment]
Conforme o mockup/tela modelo
Na parte inferior da tela
![homepage_-_institucional](https://cloud.githubusercontent.com/assets/943480/20795290/82eb9acc-b7b7-11e6-9add-12bfad2704a1.png)

**Comment by edoura** [comment]
@italoaguiar, erro constando no console.
Em relação à integração dos **members** do Github.
![erro console](https://cloud.githubusercontent.com/assets/943480/21277694/deb616bc-c3be-11e6-922a-eec488d4a53e.png)
Os outros warnings, estou verificando e corrigindo.
